version: '3.8'

services:
  app:
      build: ./train-station-front
      restart: unless-stopped
      ports:
        - '$ANGULAR_LOCAL_PORT:$ANGULAR_DOCKER_PORT'
      stdin_open: true
      tty: true

  api:
    build: ./train-station-api
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - postgresdb
    stdin_open: true
    tty: true

  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - ./db:/db